### ISSUE TITLE
#define MG_ENABLE_SNTP #define MG_ENABLE_HTTP_STREAMING_MULTIPART

### ISSUE THREAD

**Issue by Mike0675** [jeremypoulter/ArduinoMongoose#24]
Hi,
I´´m try to work with sntp. I work with Visual Studio Code and Platformio.

Compiling your example I´m got the error 'MongooseSntpClient' does not name a type; did you mean 'MongooseSntpClient_h'.
Im added #define MG_ENABLE_SNTP 1 then it compiles; but then the linker states: undefined reference to `MongooseSntpClient::getTime(char const*, std::function<void (timeval)>)'

I got the same Problem with esp_ota_http_server example, but here #define MG_ENABLE_HTTP_STREAMING_MULTIPART 1
worked. 

So how should such #defines should be done?

**Comment by Mike0675** [comment]
I see the mongoose.ws version you working with is not the latest release. Is it planed to update this, can it exchanged by my self with the newest one?

**Comment by jeremypoulter** [comment]
I set the define in the platformio.ini, see https://github.com/jeremypoulter/ArduinoMongoose/blob/master/examples/sntp_client/platformio.ini#L17 or  https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/platformio.ini#L81

As far as updating goes to the latest version, the latest version had a lot of breaking changes so haven't had a chance to update, see #14, but do want to at some point.
